using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Qurre SL")]
[assembly: AssemblyDescription("Framework for SCP:SL servers with unique functions & api")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Qurre Team")]
[assembly: AssemblyProduct("Qurre SL")]
[assembly: AssemblyCopyright("Copyright © Qurre Team 2023")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("64c5cf82-8b1a-4b79-94b5-dfe0f0e605b4")]
[assembly: AssemblyVersion("2.0.0.1")]
[assembly: AssemblyFileVersion("2.0.0.1")]
[assembly: AssemblyInformationalVersion("v2-alpha")]
